create table car (
	id bigserial not null primary key,
	car_make VARCHAR(50) NOT NULL,
	car_model VARCHAR(50) NOT NULL,
	price VARCHAR(100) NOT NULL
);
insert into car (id, car_make, car_model, price) values (1, 'Chevrolet', 'S10', '4379.52');
insert into car (id, car_make, car_model, price) values (2, 'Audi', 'R8', '7288.25');
insert into car (id, car_make, car_model, price) values (3, 'Mercedes-Benz', 'S-Class', '6222.01');
insert into car (id, car_make, car_model, price) values (4, 'Hummer', 'H2', '1149.43');
insert into car (id, car_make, car_model, price) values (5, 'Ford', 'Festiva', '4058.33');
insert into car (id, car_make, car_model, price) values (6, 'Buick', 'Skylark', '8791.69');
insert into car (id, car_make, car_model, price) values (7, 'Acura', 'Integra', '4234.48');
insert into car (id, car_make, car_model, price) values (8, 'Eagle', 'Vision', '2449.18');
insert into car (id, car_make, car_model, price) values (9, 'Audi', 'A6', '5762.97');
insert into car (id, car_make, car_model, price) values (10, 'Aston Martin', 'DB9', '9319.73');
insert into car (id, car_make, car_model, price) values (11, 'Lincoln', 'Town Car', '2369.73');
insert into car (id, car_make, car_model, price) values (12, 'Maybach', '62', '6558.58');
insert into car (id, car_make, car_model, price) values (13, 'Nissan', 'Murano', '9926.62');
insert into car (id, car_make, car_model, price) values (14, 'Toyota', 'Tacoma', '9781.58');
insert into car (id, car_make, car_model, price) values (15, 'Smart', 'Fortwo', '1410.05');
insert into car (id, car_make, car_model, price) values (16, 'Mazda', 'Tribute', '7702.01');
insert into car (id, car_make, car_model, price) values (17, 'Hyundai', 'Veracruz', '9296.77');
insert into car (id, car_make, car_model, price) values (18, 'Chevrolet', 'TrailBlazer', '5168.65');
insert into car (id, car_make, car_model, price) values (19, 'Lexus', 'GS', '2264.25');
insert into car (id, car_make, car_model, price) values (20, 'Lexus', 'CT', '6262.03');
insert into car (id, car_make, car_model, price) values (21, 'Cadillac', 'CTS-V', '1794.89');
insert into car (id, car_make, car_model, price) values (22, 'Honda', 'S2000', '1309.52');
insert into car (id, car_make, car_model, price) values (23, 'GMC', 'Acadia', '6438.40');
insert into car (id, car_make, car_model, price) values (24, 'Pontiac', 'Bonneville', '5219.17');
insert into car (id, car_make, car_model, price) values (25, 'Ford', 'Explorer Sport Trac', '4795.00');
insert into car (id, car_make, car_model, price) values (26, 'Cadillac', 'Seville', '7968.36');
insert into car (id, car_make, car_model, price) values (27, 'Ford', 'Bronco', '3658.42');
insert into car (id, car_make, car_model, price) values (28, 'Subaru', 'Legacy', '8980.43');
insert into car (id, car_make, car_model, price) values (29, 'Jaguar', 'XK', '8152.96');
insert into car (id, car_make, car_model, price) values (30, 'Chevrolet', 'Express 2500', '6195.32');
insert into car (id, car_make, car_model, price) values (31, 'Infiniti', 'QX', '6216.94');
insert into car (id, car_make, car_model, price) values (32, 'Honda', 'CR-Z', '7086.09');
insert into car (id, car_make, car_model, price) values (33, 'GMC', 'Sonoma', '5142.92');
insert into car (id, car_make, car_model, price) values (34, 'BMW', '5 Series', '4546.67');
insert into car (id, car_make, car_model, price) values (35, 'Bentley', 'Continental GTC', '3277.30');
insert into car (id, car_make, car_model, price) values (36, 'Subaru', 'Tribeca', '2573.12');
insert into car (id, car_make, car_model, price) values (37, 'Cadillac', 'DeVille', '1166.37');
insert into car (id, car_make, car_model, price) values (38, 'Suzuki', 'Swift', '5834.37');
insert into car (id, car_make, car_model, price) values (39, 'Chevrolet', 'Silverado 2500', '6306.16');
insert into car (id, car_make, car_model, price) values (40, 'Lexus', 'RX Hybrid', '8272.60');
insert into car (id, car_make, car_model, price) values (41, 'Mitsubishi', 'Truck', '6123.30');
insert into car (id, car_make, car_model, price) values (42, 'Lotus', 'Exige', '7096.84');
insert into car (id, car_make, car_model, price) values (43, 'BMW', 'Z3', '9019.34');
insert into car (id, car_make, car_model, price) values (44, 'Jeep', 'Liberty', '4292.44');
insert into car (id, car_make, car_model, price) values (45, 'Chrysler', 'Town & Country', '3931.32');
insert into car (id, car_make, car_model, price) values (46, 'Toyota', 'Avalon', '9546.71');
insert into car (id, car_make, car_model, price) values (47, 'Dodge', 'Ram Van 1500', '9112.13');
insert into car (id, car_make, car_model, price) values (48, 'Chevrolet', 'Beretta', '3902.40');
insert into car (id, car_make, car_model, price) values (49, 'Plymouth', 'Colt', '9818.19');
insert into car (id, car_make, car_model, price) values (50, 'Subaru', 'Forester', '5361.53');
insert into car (id, car_make, car_model, price) values (51, 'Ford', 'Bronco', '6825.58');
insert into car (id, car_make, car_model, price) values (52, 'Mazda', 'Protege', '6732.99');
insert into car (id, car_make, car_model, price) values (53, 'Mercury', 'Grand Marquis', '8768.29');
insert into car (id, car_make, car_model, price) values (54, 'Honda', 'Odyssey', '7694.59');
insert into car (id, car_make, car_model, price) values (55, 'Honda', 'Insight', '6578.24');
insert into car (id, car_make, car_model, price) values (56, 'Suzuki', 'Daewoo Lacetti', '9607.01');
insert into car (id, car_make, car_model, price) values (57, 'Chrysler', 'PT Cruiser', '3321.84');
insert into car (id, car_make, car_model, price) values (58, 'Lincoln', 'Navigator', '1163.87');
insert into car (id, car_make, car_model, price) values (59, 'Lotus', 'Exige', '2042.01');
insert into car (id, car_make, car_model, price) values (60, 'Mercury', 'Mountaineer', '1543.03');
insert into car (id, car_make, car_model, price) values (61, 'Volkswagen', 'GTI', '2848.38');
insert into car (id, car_make, car_model, price) values (62, 'Honda', 'Prelude', '1628.63');
insert into car (id, car_make, car_model, price) values (63, 'Hummer', 'H3', '1743.47');
insert into car (id, car_make, car_model, price) values (64, 'GMC', 'Sonoma Club Coupe', '7842.26');
insert into car (id, car_make, car_model, price) values (65, 'Toyota', 'Celica', '7779.39');
insert into car (id, car_make, car_model, price) values (66, 'Lincoln', 'Navigator L', '4984.79');
insert into car (id, car_make, car_model, price) values (67, 'BMW', '6 Series', '1530.07');
insert into car (id, car_make, car_model, price) values (68, 'Mercedes-Benz', '300SL', '7569.21');
insert into car (id, car_make, car_model, price) values (69, 'Infiniti', 'G37', '1521.91');
insert into car (id, car_make, car_model, price) values (70, 'Honda', 'Accord', '5562.98');
insert into car (id, car_make, car_model, price) values (71, 'Mercedes-Benz', 'SL-Class', '3442.11');
insert into car (id, car_make, car_model, price) values (72, 'Cadillac', 'DTS', '1490.82');
insert into car (id, car_make, car_model, price) values (73, 'Dodge', 'Caravan', '3042.30');
insert into car (id, car_make, car_model, price) values (74, 'Chevrolet', 'Equinox', '4958.75');
insert into car (id, car_make, car_model, price) values (75, 'Acura', 'Integra', '7053.97');
insert into car (id, car_make, car_model, price) values (76, 'Ford', 'E250', '1212.35');
insert into car (id, car_make, car_model, price) values (77, 'Volkswagen', 'Jetta', '6476.35');
insert into car (id, car_make, car_model, price) values (78, 'Toyota', 'Tundra', '8709.70');
insert into car (id, car_make, car_model, price) values (79, 'Subaru', 'Forester', '8785.04');
insert into car (id, car_make, car_model, price) values (80, 'Mazda', 'B-Series', '7620.82');
insert into car (id, car_make, car_model, price) values (81, 'Isuzu', 'Stylus', '6883.00');
insert into car (id, car_make, car_model, price) values (82, 'BMW', '5 Series', '2762.30');
insert into car (id, car_make, car_model, price) values (83, 'Pontiac', 'Grand Am', '2937.05');
insert into car (id, car_make, car_model, price) values (84, 'Lotus', 'Exige', '5608.95');
insert into car (id, car_make, car_model, price) values (85, 'Lincoln', 'Navigator', '7479.28');
insert into car (id, car_make, car_model, price) values (86, 'Jeep', 'Patriot', '6700.54');
insert into car (id, car_make, car_model, price) values (87, 'Ford', 'Thunderbird', '3321.14');
insert into car (id, car_make, car_model, price) values (88, 'Lexus', 'ES', '6062.25');
insert into car (id, car_make, car_model, price) values (89, 'Chevrolet', 'Tracker', '6507.15');
insert into car (id, car_make, car_model, price) values (90, 'Bentley', 'Arnage', '3280.87');
insert into car (id, car_make, car_model, price) values (91, 'Nissan', 'Versa', '3464.93');
insert into car (id, car_make, car_model, price) values (92, 'Mitsubishi', 'Diamante', '9741.96');
insert into car (id, car_make, car_model, price) values (93, 'Chevrolet', 'Express 1500', '4139.38');
insert into car (id, car_make, car_model, price) values (94, 'Volvo', 'S60', '9804.06');
insert into car (id, car_make, car_model, price) values (95, 'Honda', 'Accord', '6442.93');
insert into car (id, car_make, car_model, price) values (96, 'Mercedes-Benz', 'S-Class', '5334.77');
insert into car (id, car_make, car_model, price) values (97, 'Mitsubishi', 'Lancer', '7614.80');
insert into car (id, car_make, car_model, price) values (98, 'Lincoln', 'Mark LT', '6578.43');
insert into car (id, car_make, car_model, price) values (99, 'BMW', '530', '1307.30');
insert into car (id, car_make, car_model, price) values (100, 'Dodge', 'Caravan', '7348.80');
